apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: scan-rest
  name: scan-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scan-rest
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: scan-rest
    spec:
      containers:
      - env:
        - name: CLAMD_HOST
          value: clamav-server
        image: lokori/clamav-rest
        imagePullPolicy: ""
        name: scan-rest
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
